# -*- coding: utf-8 -*-
"""
Author: Ronak Shoghi
Date: 06.05.22
Time: 13:46


This function reads the system related meta data
"""

import platform
import socket
import uuid
import re
import getpass
from datetime import date
import os
import Database_Handler as DC
import json
import re
from collections import defaultdict

"""
This function reads Meta data in inout folder for each key and writes them in the JSON database
"""
structured_elements = {"C3D8", "C3D8R", "S4", "S4R"}
non_structured_elements = {"C3D4", "C3D10", "S3", "S3R"}

def relative_path(current_path,base_path):
    relative_path = os.path.relpath(current_path, base_path)
    return relative_path

def extract_geom_software_name(lines):
    software_patterns = [
        r"generated by:\s([\w/.-]+)\s([\d.-]+)?",  # Matches "Generated by: Abaqus/CAE 6.14-2"
        r"software:\s([\w/.-]+)\s([\d.-]+)?"  # Matches "Software: Abaqus/CAE 6.14-2"
        #Add for Kanapy
    ]
    geom_software_name, geom_software_version = "NA", "NA"
    for line in lines:
        line_lower = line.lower()
        if line.startswith('**'):
            for pattern in software_patterns:
                match = re.search(pattern, line_lower)
                if match:
                    software_name = match.group(1)
                    version = match.group(2) if match.group(2) else "NA"
                    return software_name, version

    return geom_software_name, geom_software_version

def mechanical_BC_reader(lines):
    mechanical_BC =[
        {
            "vertex_list": ["V000"],
            "constraints": ["TBD", "TBD", "TBD"]
        },
        {
            "vertex_list": ["V001"],
            "constraints": ["TBD", "TBD", "TBD"]
        },
        {
            "vertex_list": ["V101"],
            "constraints": ["TBD", "TBD", "TBD"]
        },
        {
            "vertex_list": ["V011"],
            "constraints": ["TBD", "TBD", "TBD"]
        }]

    translation_dic = {"V1": ["V001", 1], "V2": ["V101", 2], "V4": ["V011", 3], "H1": ["V000", 0]}

    Load_Type = "static"  # Default to Monotonic
    Frequency = 0
    R = 0
    Duration = 0
    for i, line in enumerate(lines):
        if "*Amplitude" in line:
            Load_Type = "cyclic"
            Frequency = []  # Reset Amplitude to an empty list
            j = i + 1
            while not lines[j].startswith("**") and not lines[j].startswith("*"):
                values = lines[j].split(',')
                for value in values:
                    try:
                        integer_part = int(float(value.strip()))
                        Frequency.append(integer_part)
                    except ValueError:
                        # Continue if there's any non-numeric value
                        continue
                j += 1
            break
        if "*Static" in line:
            j = i + 1
            values = lines[j].split(',')
            Duration = values[1]


    for i, line in enumerate(lines):
        if "*Boundary" in line:
            j = i + 1
            while not lines[j].startswith("**") and not lines[j].startswith("*"):
                values = lines[j].split(',')
                mechanical_BC[translation_dic[values[0]][1]]["constraints"][int(values[1])-1] = "fixed"
                j += 1
        elif "*Cload" in line:
            j = i + 1
            while not lines[j].startswith("**") and not lines[j].startswith("*"):
                values = lines[j].split(',')
                mechanical_BC[translation_dic[values[0]][1]]["constraints"][int(values[1])-1] = "loaded"
                mechanical_BC[translation_dic[values[0]][1]]["loading_type"] = "force"
                mechanical_BC[translation_dic[values[0]][1]]["loading_mode"] = Load_Type
                # Check if "applied_load" exists, and handle accordingly
                if "applied_load" not in mechanical_BC[translation_dic[values[0]][1]]:
                    mechanical_BC[translation_dic[values[0]][1]]["applied_load"] = [{}, {}, {}]
                    mechanical_BC[translation_dic[values[0]][1]]["applied_load"][int(values[1])-1] = {"magnitude": values[2], "frequency": Frequency, "duration": Duration, "R": R}
                else:
                    mechanical_BC[translation_dic[values[0]][1]]["applied_load"][int(values[1])-1] = {"magnitude": values[2], "frequency": Frequency, "duration": Duration, "R": R}
                j += 1

            for BC in mechanical_BC:
                if "applied_load" in BC:
                    temp = BC["applied_load"]
                    # Remove empty dictionaries
                    temp = [item for item in temp if item]
                    BC["applied_load"] = temp

    return mechanical_BC

def umat_material_translator(id):
    "A function to give the material's name based on the id numbers in ICAMS UMAT"
    if id == 1:
        material_identifier = "Aluminum"
    elif id == 2:
        material_identifier = "Copper"
    elif id == 3:
        material_identifier = "Ferrite"
    elif id == 4:
        material_identifier = "Austenite"
    elif id == 5:
        material_identifier = "Superalloy"
    elif id == 5:
        material_identifier = "Nickel"
    return material_identifier

def constituitve_model_extraction_from_fortran(file_path, target_material_number):
    "A funtion to extract constiruitve model based on the specification of ICAMS UMAT. "
    "The constituitve model is constructed according to the schema:https://github.com/Ronakshoghi/MetadataSchema/blob/main/crystal_plasticity_constitutive_model_metadata_schema.json"
    constitutive_model = {
        "$schema": "https://github.com/Ronakshoghi/MetadataSchema/blob/main/crystal_plasticity_constitutive_model_metadata_schema.json",
        "elastic_model_name": "Anisotropic Elasticity",
        "elastic_parameters": {},
        "plastic_model_name": "Crystal Plasticity",
        "plastic_parameters": {},
        "units" : {"Stress": "MPa", "Stiffness": "MPa"}
    }
    elastic_param_map = {
        "c11": "C11",
        "c12": "C12",
        "c44": "C44"
    }
    plastic_param_map = {
        "shrt0": "reference_shear_rate",
        "crss0": "initial_critical_resolved_shear_stress",
        "crsss": "saturated_slip_resistance",
        "pwfl": "strain_rate_sensitivity_exponent",
        "hdrt0": "reference_hardening_rate",
        "pwhd": "hardening_exponent"
    }

    with open(file_path, 'r') as file:
        lines = file.readlines()
    extracting = False
    inside_module = False
    for line in lines:
        if 'Material library:' in line:
            try:
                material_number = int(line.split('#')[1].split('==>')[0].strip())
                extracting = (material_number == target_material_number)
                inside_module = False
            except (IndexError, ValueError):
                extracting = False

        if extracting and re.match(r"\s*module\s+mod_", line):
            inside_module = True

        if extracting and inside_module:
            match = re.match(r"\s*real\(8\),\s*parameter::\s*(\w+)\s*=\s*([\d.eEdD+-]+)", line.split("!")[0])
            if match:
                param_name, param_value = match.groups()
                param_value = float(param_value.replace('d', 'e').replace('D', 'E'))
                if param_name in elastic_param_map:
                    constitutive_model["elastic_parameters"][elastic_param_map[param_name]] = param_value
                elif param_name in plastic_param_map:
                    constitutive_model["plastic_parameters"][plastic_param_map[param_name]] = param_value

        if inside_module and re.match(r"\s*end\s+module\s+mod_", line, re.IGNORECASE):
            inside_module = False
            extracting = False
    return constitutive_model


def Meta_reader(Key):
    parameters = Key.split('_')
    Key_Parsed = {"Hash_Load": parameters[0],"Hash_Orientation": parameters[1]}
    uname = platform.uname()
    Meta = {}
    Current_Path = os.getcwd()
    Keys_Path ="{}/Keys".format(Current_Path)
    os.chdir(Keys_Path)
    Key_path = os.path.abspath(Key)
    Key_Input_Path = "{}/inputs".format(Key_path)
    Key_Results_Path = "{}/results".format(Key_path)
    os.chdir(Key_Input_Path)
    User_Specific_File = open("User_Specific.txt")
    # Read_User_Specific infromation
    Meta["identifier"] = Key
    lines_user = User_Specific_File.readlines()
    pattern = re.compile(r'^"(\w+)":\s*"([^"]+)"')
    list_keys = {"creator", "creator_ORCID", "creator_affiliation", "creator_institute","creator_group", "contributor",
                    "contributor_ORCID", "contributor_affiliation", "contributor_institute", "contributor_group","shared_with",
                     "relation", "keywords"}
    single_keys = {"$schema", "title", "description","rights","rights_holder","funder_name","fund_identifier","publisher"}
    for line_user in lines_user:
        match = pattern.match(line_user.strip())
        if match:
            key = match.group(1)
            value = match.group(2)
            if key in list_keys:
                extracted_meta = re.findall(r'[^,"]+,\s*[^,"]+|[^,"]+', value)
                Meta[key] = [v.strip() for v in extracted_meta]
            elif key in single_keys:
                Meta[key] = value
    Meta['Date'] = date.today().strftime("%Y-%m-%d")
    #system_related
    Meta["software"] = "Abaqus"
    Input_File=open('{}_Abaqus_Input_File.inp'.format(Key))
    inp_lines = Input_File.readlines()
    Abaqus_Version = (inp_lines[2].split(':'))[1]
    Meta['software_version'] = Abaqus_Version
    Meta['system']: uname.system
    Meta["system_version"] = uname.release
    Meta["processor_specification"] = uname.processor
    Meta['input-path'] = relative_path(Key_Input_Path, Current_Path)
    Meta['results-path'] = relative_path(Key_Results_Path, Current_Path)
    #geometry related
    Element_Number = None
    for i, line in enumerate(inp_lines):
        if "*Nset" in line:
            previous_line = inp_lines[i - 1]
            Element_Number = int(previous_line.split(',')[0].strip())
            break
    for i, line in enumerate(inp_lines):
        if line.startswith("*Element, type="):
            element_type = line.split("=")[1].strip()
            if element_type in structured_elements:
                discretization_type = "Structured"
            elif element_type in non_structured_elements:
                discretization_type = "Unstructured"
            else:
                discretization_type = "Unknown Type"

    Element_Size = 0.095 # can be get from max and min, element volume, then get some average by dividing by number of nodes
    #x = round((Grain_Number ** (1/3)) * Element_Size, 4)
    #RVE_Size = (x, x, x) # diff
    y = 0.095
    RVE_size = (y,y,y)
    Meta['RVE_size'] = RVE_size
    Meta["RVE_continuity"] = "true" # For now! Need update based on inp file.
    Meta["discretization_type"] = discretization_type
    Meta["discretization_unit_size"] = (Element_Size,Element_Size,Element_Size)
    Meta["discretization_count"] = Element_Number #should be given in the main.
    origin = {}
    geom_software_name, geom_software_version =extract_geom_software_name(inp_lines)
    origin["software"] = geom_software_name
    origin["version"] = geom_software_version
    origin["system"] = uname.system
    origin["system_version"] = uname.release
    origin["input_path"] = relative_path(Key_Input_Path, Current_Path)
    origin["results_path"] = relative_path(Key_Results_Path, Current_Path)
    Meta["origin"] = origin
    Meta["global_temperature"] = 298 # how this should be detected normally?
    # Mechanical_BC
    Load_File = open('{}_remPart_file.inp'.format(Key))
    rempart_lines = Load_File.readlines()[1:]
    Meta["mechanical_BC"] = mechanical_BC_reader(rempart_lines)
    # Material related info
    Material_File = open('Material.inp')
    material_lines = Material_File.readlines()[1:]
    Material = {}
    for i, line in enumerate(material_lines):
        if "*User Material" in line and (i + 1) < len(material_lines):
            material_id = int(material_lines[i + 1].split(',')[0])
            break
    material_identifier = umat_material_translator(material_id)
    Material["Material_Identifier"] = material_identifier
    fortran_file_path = os.path.join(Key_Input_Path, 'mod_alloys.f')
    constituitve_model = constituitve_model_extraction_from_fortran(fortran_file_path, material_id)
    Material["constituitve_model"] =constituitve_model
    Orientation_File = open('Orientation.txt')
    Phi1 = []
    Phi2 = []
    Phi3 = []
    orientation = {}
    euler_angles = {}
    ori_lines = Orientation_File.readlines()[1:]
    for line in ori_lines:
        Phi1.append(float(line.split('  ')[0]))
        Phi2.append(float(line.split('  ')[1]))
        Phi3.append(float(line.split('  ')[2]))
    euler_angles['Phi1'] = Phi1
    euler_angles['Phi2'] = Phi2
    euler_angles['Phi3'] = Phi3
    orientation["euler_angles"] = euler_angles
    orientation["grain_count"] = len(ori_lines)
    orientation["orientation_identifier"] = Key_Parsed["Hash_Orientation"]
    orientation["texture_type"] = "Random"
    orientation["software"] = "MTEX"
    orientation["software_version"] = "5.15.2"
    Material['orientation'] = orientation
    Meta['Material'] = Material
    os.chdir(Current_Path)
    return (Meta)
def Meta_Writer (key, json_file):
    Meta = Meta_reader(key)
    with open(json_file, 'w') as output_file:
        Current_Dict = DC.Read_Database_From_Json("Data_Base.json")
        print(Current_Dict)
        if key in Current_Dict.keys():
            print("The key is already found in JSON file")
            temp_dic = Current_Dict[key]
            for meta in Meta:
                temp_dic[meta] = Meta[meta]
            Current_Dict.update(temp_dic)
            json.dump(Current_Dict, output_file)
        else:
            print("The key was not found in JSON file")
